version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb_challenger
    volumes: 
      - /home/challenger/database:/data/db
    restart: unless-stopped